<?php
/**
 * Created by PhpStorm.
 * User: havartjeremie
 * Date: 23/05/2018
 * Time: 13:37
 */

namespace App\UI\Form\Handler;

use App\Domain\Builder\Interfaces\ObserveBuilderInterface;
use App\Domain\Repository\ObserveRepository;
use App\Domain\Repository\TaxRefRepository;
use App\UI\Form\Handler\Interfaces\ObserveTypeHandlerInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class ObserveTypeHandler implements ObserveTypeHandlerInterface
{
    /**
     * @var string
     */
    private $imageFolder;

    /**
     * @var ObserveBuilderInterface
     */
    private $observeBuilder;

    /**
     * @var ObserveRepository
     */
    private $observeRepository;

    /**
     * @var FlashBagInterface
     */
    private $flash;

    /**
     * @var UploadedFile
     */
    private $fileOutput;

    /**
     * @var TokenStorageInterface
     */
    private $token;

    /**
     * @var TaxRefRepository
     */
    private $taxRefRepository;

    /**
     * @var string
     */
    private $media;

    /**
     * ObserveTypeHandler constructor.
     *
     * @param ObserveBuilderInterface $observeBuilder
     * @param ObserveRepository       $observeRepository
     * @param string                  $imageFolder
     * @param FlashBagInterface       $flashBag
     * @param TokenStorageInterface   $token
     * @param TaxRefRepository        $taxRefRepository
     * @param string                  $media
     */
    public function __construct(
        TokenStorageInterface   $token,
        ObserveBuilderInterface $observeBuilder,
        ObserveRepository       $observeRepository,
        string                  $imageFolder,
        FlashBagInterface       $flashBag,
        TaxRefRepository        $taxRefRepository,
        string                  $media
    ) {
        $this->token             = $token;
        $this->observeBuilder    = $observeBuilder;
        $this->observeRepository = $observeRepository;
        $this->imageFolder       = $imageFolder;
        $this->flash             = $flashBag;
        $this->taxRefRepository  = $taxRefRepository;
        $this->fileOutput        = null;
        $this->media             = $media;
    }

    /**
     * @param FormInterface $form
     *
     * @return bool|mixed
     */
    public function handle(FormInterface $form): bool
    {
        if ($form->isSubmitted() && $form->isValid()) {

            /**
             * @var UploadedFile $file
             */
            $file = $form->getData()->img;

            if ($file) {
                $this->fileOutput = $file->move(
                    $this->imageFolder,
                    $this->generateUniqueFileName()."."
                    .$file->guessExtension()
                );
            }

            $user = $this->token->getToken()->getUser();
            $bird = $form->getData()->ref;
            $result = $this->taxRefRepository->findOneBy(['nomComplet' => $bird]);

            $this->observeBuilder->create(
                $user,
                $result,
                $form->getData()->description,
                $form->getData()->latitude,
                $form->getData()->longitude,
                $this->media.$this->fileOutput->getFilename()
            );

            $this->observeRepository->save($this->observeBuilder->getObserve());

            $this->flash->add('observe','votre observation à été ajoutée');

            return true;
        }
        return false;
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
